#!/usr/bin/env python3
"""CPS3 character RAM load experiments (src/dmap.c), read back from the screen: every tile carries its own 16-bit
label (a 4 x 4 grid of 4 x 4-pixel blocks, bit 15 top-left, row by row) in colours that say where it came from, so one
screenshot shows which tile the video draws in each tilemap cell, whatever the hardware did. tools/dmap_check.py
decodes MAME snapshots and jtcps3 screenshots and compares them with each step's expectation.

    dmap.py <out_dir>    -> <out_dir>/dmap_scene.h, <out_dir>/dmap.bin (graphics flash from SIMM 3), <out_dir>/steps.txt

Label colours (pens: bit 0 / bit 1): written by the CPU 1 / 2 (greens), in the graphics flash as plain tiles 3 / 4
(reds), in the flash as compressed data 5 / 6 (blues); a cell left at pen 0 shows the backdrop.
Flash: plain tile t at byte 256 t (t = 0 .. FLASH_TILES - 1) labelled t; compressed streams (command 2, MAME
do_char_dma: bytes < 0x40 literal, 0x40 | n = the last literal n + 1 more times; a table set by command 4 though no
0x80 byte uses it) at RLE_AT, labels RLE_LABEL + i.
Screen: tilemap 0, 24 x 13 cells (lines 0-207) from the step's shown tile; text row 27: the step and frame numbers.
Steps (STEP_FRAMES frames each; the program stays in the last), set by STEPS below:
  (name, kind, source, destination, tiles shown from, expected origin, expected first label)
  kind: 'cpu' (the CPU writes labelled tiles), 'dma0' (uncompressed DMA), 'dma2' (compressed DMA); with '_off' the
  display list is empty for BLANK_FRAMES frames and the load happens in the middle of them.
The default order: the uncompressed DMA twice over the tiles on screen, into fresh tiles, the CPU and DMA loads with
the display off, then the compressed DMA twice. DMAP_STEPS=<name,...> (environment) picks and orders steps by name.
"""
import os
import sys

COLS, ROWS = 24, 13
N = COLS * ROWS                    # 312 tiles shown
STEP_FRAMES = 300
BLANK_FRAMES = 60
FLASH_TILES = 0x4000               # plain labelled tiles: 4 MB
RLE_AT = 0x500000                  # compressed streams
TABLE_AT = 0x4f0000
RLE_LABEL = (0x5000, 0x6000)
CPU, PLAIN, RLE = 0, 1, 2
PENS = {CPU: (1, 2), PLAIN: (3, 4), RLE: (5, 6)}
COLOURS = {0: (2, 2, 6), 1: (0, 10, 0), 2: (8, 31, 8), 3: (12, 0, 0), 4: (31, 10, 10), 5: (0, 0, 14), 6: (10, 16, 31)}

ALL = {   # name: (kind, source (label / stream), destination tile, shown from, origin, first label)
    'boot':      ('cpu', 0x100, 0x100, 0x100, CPU, 0x100),
    'over1':     ('dma0', 0x0000, 0x100, 0x100, PLAIN, 0x0000),
    'over2':     ('dma0', 0x1000, 0x100, 0x100, PLAIN, 0x1000),
    'fresh':     ('dma0', 0x2000, 0x4000, 0x4000, PLAIN, 0x2000),
    'cpu_off':   ('cpu_off', 0x7000, 0x100, 0x100, CPU, 0x7000),
    'dma0_off':  ('dma0_off', 0x3000, 0x100, 0x100, PLAIN, 0x3000),
    'rle1':      ('dma2', 0, 0x100, 0x100, RLE, RLE_LABEL[0]),
    'rle2':      ('dma2', 1, 0x100, 0x100, RLE, RLE_LABEL[1]),
    'cpu_on':    ('cpu', 0x7400, 0x100, 0x100, CPU, 0x7400),
}
DEFAULT = ['boot', 'over1', 'over2', 'fresh', 'cpu_off', 'dma0_off', 'rle1', 'rle2']


def steps():
    names = os.environ.get('DMAP_STEPS', ','.join(DEFAULT)).split(',')
    assert names[0] == 'boot'
    return [(n,) + ALL[n] for n in names]


def tile(label, origin):
    p0, p1 = PENS[origin]
    out = bytearray(256)
    for y in range(16):
        for x in range(16):
            bit = 15 - (y // 4 * 4 + x // 4)
            out[16 * y + x] = p1 if label >> bit & 1 else p0
    return bytes(out)


def rle(px):
    """command 2 data for the bytes px (all < 0x40): runs of 2 or more as a literal and one repeat byte"""
    out, i = bytearray(), 0
    while i < len(px):
        n = 1
        while i + n < len(px) and px[i + n] == px[i] and n < 65:
            n += 1
        out.append(px[i])
        if n > 1:
            out.append(0x40 | (n - 2))
        i += n
    return bytes(out)


def flash():
    """DMA byte a is file byte a ^ 1 of tools/mkcps3.py's user5 (measured in MAME, src/dtest.c)"""
    img = bytearray(RLE_AT + 0x100000)
    for t in range(FLASH_TILES):
        img[256 * t:256 * (t + 1)] = tile(t, PLAIN)
    for k, base in enumerate(RLE_LABEL):
        s = rle(b''.join(tile(base + i, RLE) for i in range(N)))
        assert len(s) < 0x80000
        img[RLE_AT + 0x80000 * k:RLE_AT + 0x80000 * k + len(s)] = s
    img[TABLE_AT:TABLE_AT + 256] = bytes(range(256))         # an unused decompression table
    out = bytearray(len(img))
    out[0::2], out[1::2] = img[1::2], img[0::2]
    return bytes(out)


def header():
    st = steps()
    kinds = {'cpu': 0, 'dma0': 1, 'dma2': 2}
    o = ['/* generated by tools/dmap.py */', '#include <stdint.h>', f'#define M_COLS {COLS}', f'#define M_ROWS {ROWS}',
         f'#define M_N {N}', f'#define M_STEP_FRAMES {STEP_FRAMES}', f'#define M_BLANK_FRAMES {BLANK_FRAMES}',
         f'#define M_STEPS {len(st)}', f'#define M_RLE_AT {RLE_AT:#x}', f'#define M_TABLE_AT {TABLE_AT:#x}',
         'struct m_step { uint8_t kind, off; uint16_t src, dest, shown, origin, label; };',
         'static const struct m_step m_step[M_STEPS] = {']
    for name, kind, src, dest, shown, origin, label in st:
        o.append(f'    {{{kinds[kind.replace("_off", "")]}, {int(kind.endswith("_off"))}, {src:#x}, {dest:#x}, '
                 f'{shown:#x}, {origin}, {label:#x}}},   /* {name} */')
    o.append('};')
    o.append('static const uint8_t m_pens[3][2] = {' + ', '.join(f'{{{a}, {b}}}' for a, b in PENS.values()) + '};')
    o.append('static const uint16_t m_colours[8] = {' +
             ', '.join(f'{(b << 10) | (g << 5) | r:#x}' for r, g, b in (COLOURS[k] for k in range(7))) + ', 0};')
    return '\n'.join(o) + '\n'


def main():
    out = sys.argv[1]
    os.makedirs(out, exist_ok=True)
    open(os.path.join(out, 'dmap_scene.h'), 'w').write(header())
    f = flash()
    open(os.path.join(out, 'dmap.bin'), 'wb').write(f)
    with open(os.path.join(out, 'steps.txt'), 'w') as s:
        for name, kind, src, dest, shown, origin, label in steps():
            s.write(f'{name} {kind} {origin} {label}\n')
    print(f'{out}: {len(steps())} steps, graphics flash {len(f)} bytes')


if __name__ == '__main__':
    main()
