#!/usr/bin/env python3
"""CPS3 character DMA test (src/dtest.c): tiles copied from the graphics flash (SIMM 3) into character RAM by the
video chip's character DMA, uncompressed (list command 0), while the display runs, as a game loads a level's tiles.
The program writes the DMA list into character RAM (byte 0x1000, Red Earth's place) and starts it with Red Earth's two
register writes (0x040c0096 = list word address, 0x040c0098 = 0x0040); it waits for the status bit (0x040c000c bit 1)
to clear and acknowledges IRQ 10 (0x05110000). After each DMA it reads the tiles back and reports a difference on the
text layer (MAME: none, so the expected screens have no text).

    dtest.py <out_dir>   -> <out_dir>/dtest_scene.h, <out_dir>/dtest.bin (the graphics flash from SIMM 3),
                            <out_dir>/expect_<phase>.png

Screen: tilemap 0 (24 x 10 tiles, lines 0-159), then 48 sprites of one tile (two rows of 24, at y 176 and 196):
288 tiles, each from one of five sets (A-E, its own colours: tile pixel values 1 + 48 k ...), with a grid line on
each tile's top row and left column. The pixel formula is shared with src/dtest.c (pen()), which computes the tiles
it uploads and the read-back's expected values.
Phases (PHASE_FRAMES frames each; the program stays in the last):
  0  set A, written by the CPU at start (tiles 0x100-0x21f)
  1  set B copied by one DMA list of two records (tilemap's 240 tiles, sprites' 48) over the tiles on screen
  2  set C copied into tiles never written nor drawn (0x4000-0x411f), the tilemap and sprites switched to them
  3  set D copied over the tiles on screen (0x100-0x21f) by one 16-tile DMA a frame for 18 frames (streaming)
  4  one record of 1 MB (4,096 tiles from 0xf80, across the 1 MB bank boundary at 0x1000): set E at 0xfa0-0x10bf,
     shown, the rest filler (read back only)
"""
import os
import sys

import numpy as np
from PIL import Image

W, H = 384, 224
PHASE_FRAMES = 600
COLS, ROWS = 24, 10                 # tilemap tiles on screen
NSPR = 48                           # sprites: two rows of 24
N = COLS * ROWS + NSPR              # 288 tiles a set
SPR_Y = (176, 196)
BAND_LINES = 160
PAL = 1
BASE = [0x100, 0x100, 0x4000, 0x100, 0xfa0]    # per phase: the first tile shown
BIG_DEST, BIG_N = 0xf80, 4096                   # phase 4's record: tiles 0xf80-0x1f7f
# graphics flash (DMA source addresses from SIMM 3's start)
SRC_B, SRC_C, SRC_D, SRC_BIG = 0x000000, 0x020000, 0x040000, 0x100000
STREAM_TILES, STREAM_FRAMES = 16, N // 16


def bgr(r, g, b):
    return (b << 10) | (g << 5) | r


def pen(k, j, x, y):
    """set k (0-4), tile j of the set: pixel (x, y); src/dtest.c pen() is the same"""
    if x == 0 or y == 0:
        return 250
    return 1 + 48 * k + ((x // 4 + y // 4 + j) & 1) * 24 + j % 24


def tile(k, j):
    return bytes(pen(k, j, x, y) for y in range(16) for x in range(16))


def big_tile(i):
    """phase 4's record, tile i (0-4095): set E at its shown tiles, filler (set A's formula, j = i + 1000) elsewhere"""
    j = BIG_DEST + i - BASE[4]
    return tile(4, j) if 0 <= j < N else tile(0, i + 1000)


def colours():
    c = {0: bgr(2, 2, 10)}
    for i in range(1, 256):
        c[PAL * 256 + i] = bgr((i * 7) % 32, (i * 13 + 5) % 32, (i * 3 + 8) % 32)
    return c


def flash():
    """the graphics flash as the DMA reads it: DMA byte a is file byte a ^ 1 (measured in MAME: a ^ 2, from the sound
    chip's and the DMA's byte swizzles, gave each 32-bit word's bytes reversed); the sound chip reads file byte a"""
    img = bytearray(SRC_BIG + BIG_N * 256)
    for base, k in ((SRC_B, 1), (SRC_C, 2), (SRC_D, 3)):
        for j in range(N):
            img[base + 256 * j:base + 256 * (j + 1)] = tile(k, j)
    for i in range(BIG_N):
        img[SRC_BIG + 256 * i:SRC_BIG + 256 * (i + 1)] = big_tile(i)
    out = bytearray(len(img))
    out[0::2], out[1::2] = img[1::2], img[0::2]
    return bytes(out)


def compose(phase):
    k = phase if phase < 5 else 4
    scr = np.zeros((H, W), np.int64)
    T = [np.frombuffer(tile(k, j), np.uint8).reshape(16, 16).astype(np.int64) for j in range(N)]
    for r in range(ROWS):
        for c in range(COLS):
            scr[16 * r:16 * r + 16, 16 * c:16 * c + 16] = PAL * 256 + T[r * COLS + c]
    for s in range(NSPR):
        x, y = 16 * (s % COLS), SPR_Y[s // COLS]
        scr[y:y + 16, x:x + 16] = PAL * 256 + T[COLS * ROWS + s]
    lut = np.zeros(0x20000, np.uint32)
    for i, c in colours().items():
        lut[i] = ((c & 0x1f) << 3) << 16 | (((c >> 5) & 0x1f) << 3) << 8 | ((c >> 10) & 0x1f) << 3
    rgb = lut[scr]
    a = np.stack([(rgb >> 16) & 0xff, (rgb >> 8) & 0xff, rgb & 0xff], axis=-1).astype(np.uint8)
    return Image.fromarray(a, 'RGB')


def header():
    o = ['/* generated by tools/dtest.py */', '#include <stdint.h>',
         f'#define D_PHASE_FRAMES {PHASE_FRAMES}', '#define D_PHASES 5', f'#define D_COLS {COLS}',
         f'#define D_ROWS {ROWS}', f'#define D_NSPR {NSPR}', f'#define D_N {N}', f'#define D_BAND_LINES {BAND_LINES}',
         f'#define D_SPR_Y0 {SPR_Y[0]}', f'#define D_SPR_Y1 {SPR_Y[1]}', f'#define D_PAL {PAL}',
         f'#define D_BIG_DEST {BIG_DEST:#x}', f'#define D_BIG_N {BIG_N}',
         f'#define D_SRC_B {SRC_B:#x}', f'#define D_SRC_C {SRC_C:#x}', f'#define D_SRC_D {SRC_D:#x}',
         f'#define D_SRC_BIG {SRC_BIG:#x}', f'#define D_STREAM_TILES {STREAM_TILES}',
         f'#define D_STREAM_FRAMES {STREAM_FRAMES}',
         'static const uint16_t d_base[D_PHASES] = {' + ', '.join(f'{b:#x}' for b in BASE) + '};']
    c = colours()
    o.append(f'#define D_COLOURS_N {len(c)}')
    o.append(f'static const uint32_t d_colours[{len(c)}] = {{  /* index << 15 | BGR555 */')
    o.extend(f'    {(i << 15) | v:#x}u,' for i, v in sorted(c.items()))
    o.append('};')
    return '\n'.join(o) + '\n'


def main():
    out = sys.argv[1]
    os.makedirs(out, exist_ok=True)
    open(os.path.join(out, 'dtest_scene.h'), 'w').write(header())
    f = flash()
    open(os.path.join(out, 'dtest.bin'), 'wb').write(f)
    for k in range(5):
        compose(k).save(os.path.join(out, f'expect_{k}.png'))
    print(f'{out}: {N} tiles a set, graphics flash {len(f)} bytes, 5 phases')


if __name__ == '__main__':
    main()
