#!/usr/bin/env python3
"""CPS3 flash sound load test (src/ftest.c): can the program rewrite part of SIMM 3 while running and have the sound
chip play the new bytes? The use: effects resident in SIMM 3, each stage's music copied into a SIMM 3 slot from
SIMMs 4-6 at a stage change (jtcps3 plays samples only from the first 16 MB).
    ftest.py <out_dir>      -> <out_dir>/ftest.h, ftest.bin, ftest_plays.txt

Every sample is one of tools/atest.py's beep codes (n high beeps, then m low): the code heard names the bytes the
chip read. ftest.bin, the sample flash (SIMMs 3-6):
    0 MB   resident  code 0   1 high 1 low   (never written: the effects)
    8 MB   slot 1    code 8   2 high 1 low   (erased and loaded twice)
   10 MB   slot 2    code 10  2 high 3 low   (loaded once: the second 1 MB half of a chip pair, bank register odd)
   12 MB   slot 3    code 12  2 high 5 low   (plain writes, no flash commands)
   16 MB   source A  code 16  3 high 1 low   (SIMM 4)
   48 MB   source B  code 48  7 high 1 low   (SIMM 6)
ftest.h: the offsets, lengths, each source's sum of 16-bit halfwords as the CPU reads them through the flash window
(halfword 2w = sample bytes 4w + 1, 4w; 2w + 1 = 4w + 3, 4w + 2: MAME cps3.cpp gfxflash_w / copy_from_nvram), and the
plays (screen text: label, code if the loads work, code in MAME).
ftest_plays.txt: the plays in order, with the code expected if the loads work and the code MAME plays.
"""
import os
import struct
import sys

import atest

MB = 1 << 20
SAMPLES = [('RES', 0, 0), ('SLOT1', 8 * MB, 8), ('SLOT2', 10 * MB, 10), ('SLOT3', 12 * MB, 12),
           ('SRCA', 16 * MB, 16), ('SRCB', 48 * MB, 48)]


def name(b):
    return f'{b // 8 + 1}H {b % 8 + 1}L'


# (label, sample played, code if loads work, code in MAME): MAME's sample copy changes only at the window words a
# write touches (gfxflash_w), so an erased slot still plays its old code there. Plain writes: none expected in MAME
# (None): its flash model (intelfsh.cpp) takes any data byte 0x10 / 0x40 / 0x90 / 0x20 ... as an Intel command, with
# or without the AMD unlock, so sample bytes written plainly program some of the bytes after them
PLAYS = [('RESIDENT', 'RES', 0, 0), ('SLOT1 BEFORE', 'SLOT1', 8, 8), ('SLOT2 BEFORE', 'SLOT2', 10, 10),
         ('SLOT3 BEFORE', 'SLOT3', 12, 12),
         ('SLOT1 ERASED', 'SLOT1', None, 8),
         ('SLOT1 = A', 'SLOT1', 16, 16), ('RESIDENT', 'RES', 0, 0),
         ('SLOT1 = B', 'SLOT1', 48, 48),
         ('SLOT2 = A', 'SLOT2', 16, 16),
         ('SLOT3 = A RAW', 'SLOT3', 16, None)]


def main():
    out = sys.argv[1]
    os.makedirs(out, exist_ok=True)
    img = bytearray()
    lens, sums = {}, {}
    for key, at, b in SAMPLES:
        d = bytes(v & 0xff for v in atest.code(b))
        d += bytes(-len(d) % 4)
        if len(img) < at:
            img += bytes(at - len(img))
        img[at:at + len(d)] = d
        lens[key] = lens[b] = len(d)
        sums[key] = sum(struct.unpack(f'<{len(d) // 2}H', d)) & 0xffffffff
    open(os.path.join(out, 'ftest.bin'), 'wb').write(bytes(img))
    with open(os.path.join(out, 'ftest.h'), 'w') as f:
        f.write('/* generated by tools/ftest.py: sample-flash byte offsets (chip address - 0x400000), lengths, and for\n'
                '   the sources the sum of the halfwords read through the flash window */\n')
        for key, at, b in SAMPLES:
            f.write(f'#define F_{key} 0x{at:07x}u\n#define F_{key}_LEN {lens[key]}u   /* code {b}: {name(b)} */\n')
        for key in ('SRCA', 'SRCB'):
            f.write(f'#define F_{key}_SUM 0x{sums[key]:08x}u\n')
        f.write('static const struct f_play { const char *text; uint32_t off, len; } f_plays[] = {\n')
        for k, (label, s, ok, mame) in enumerate(PLAYS):
            text = f'{k + 1:02d} {label:13s} {name(ok) if ok is not None else "SILENT":6s} MAME {name(mame) if mame is not None else "?"}'
            own = next(b for key, _, b in SAMPLES if key == s) if mame is None else None
            n = max(lens[c] for c in (ok, mame, own) if c is not None)  # long enough for the codes it may play
            f.write(f'    {{"{text}", F_{s}, {n}}},\n')
        f.write('};\n')
    with open(os.path.join(out, 'ftest_plays.txt'), 'w') as f:
        for k, (label, s, ok, mame) in enumerate(PLAYS):
            f.write(f'{k + 1:2d} {label:14s} {s:6s} loads work: {name(ok) if ok is not None else "silence":7s}'
                    f'  MAME: {name(mame) if mame is not None else "?"}\n')
    print(f'{out}: {len(img)} bytes of sample flash, {len(PLAYS)} plays')


if __name__ == '__main__':
    main()
